### ISSUE TITLE
Add the "right" serialization.configs for production

### ISSUE THREAD

**Issue by squadwuschel** [muso31/Helixbase#11]
Hi,

I've git some understanding problems. When I take your example project I cann install it locally works fine. But as far as I understand you must include the hole content and media tree inside unicorn so that everyone can see the demodata you provided. But thats not working in production environment, because you should not use unicorn to sync your content so far I know.

so the config for Helixbase.Serialization should look like a bit different at minimum for those two node: 

      <include name="$(layer).$(module).Content" database="master" path="/sitecore/content/Helixbase"/>
      <include name="$(layer).$(module).Media" database="master" path="/sitecore/media library/$(layer)/$(module)"/>

could you provide a demo example config in your solution which shows how the config should look like in a "real" world solution where you are not syncing the content with unicorn?

**Comment by muso31** [comment]
Hi you can find the root node serialized in the project layer, and media serialization is set at module level. You’d need to tweak the current setup for your own needs but first need to understand the differences in the master and new item evaluator. Unicorn will be used in a production environment providing you have a config role for CM and you’ve configured a config using the new evaluator correctly. If you research Unicorn configuration you can then configure your own serialization strategy accordingly. As this is an individual thing it isn’t configured in this accelerator and I assume most people won’t be using the Helixbase demo site for their clients and this will be removed anyway
