### ISSUE TITLE
Unicorn not running with Sitecore 9.1

### ISSUE THREAD

**Issue by Jen-Pearson** [muso31/Helixbase#15]
Following the install steps and on step 5 -  navigating to, after logging in as admin:
http://demo.helixbase.sc/unicorn.aspx gives me

![image](https://user-images.githubusercontent.com/8033039/51445727-9675a580-1d5c-11e9-8e41-19fcd2b0cfd6.png)

I posted on stackexchange 
https://sitecore.stackexchange.com/questions/16098/setting-up-helixbase-with-sitecore-9-1-and-unsure-how-to-run-unicorn/16103#16103

But following the recommendation of upgrading unicorn and rainbow in the Helixbase.Feature.Fun and Helixbase.Foundation.Serialization project files, and adding a Unicorn.Ui.IdentityServer.config file did not solve my problem.

Please note that the installer for 9.1 adds a .sc suffix for the website - so I had to update the gulp config to have the site being published successfully.  After restarting IIS, if I have the Unicorn.Ui.IdentityServer.config disabled then I get an error saying I need to log in as an administrator.

If I have that config enabled I get:

![image](https://user-images.githubusercontent.com/8033039/51447854-2ffd8100-1d76-11e9-8011-d7e74a905086.png)

For reference my config has: 

```
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/" xmlns:role="http://www.sitecore.net/xmlconfig/role/" xmlns:security="http://www.sitecore.net/xmlconfig/security/">
	<sitecore role:require="Standalone or ContentManagement" security:require="Sitecore">
		<pipelines>
			<!--
				The Unicorn control panel path must be added to the list of site neutral paths for the Unicorn control panel to work with authentication in 9.1.
				This must match the activationUrl defined in the UnicornControlPanelPipelineProcessor defined in Unicorn.UI.config.
			-->
			<owin.cookieAuthentication.validateIdentity>
				<processor type="Sitecore.Owin.Authentication.Pipelines.CookieAuthentication.ValidateIdentity.ValidateSiteNeutralPaths, Sitecore.Owin.Authentication">
					<siteNeutralPaths hint="list">
						<path hint="unicorn">/unicorn.aspx</path>
					</siteNeutralPaths>
				</processor>
			</owin.cookieAuthentication.validateIdentity>
		</pipelines>
	</sitecore>
</configuration>
```

**Comment by muso31** [comment]
Hi I have responded to the StackExchange [post](https://sitecore.stackexchange.com/a/16142/1274) - this is not an issue with Helix Base. Also, for info I have updated to Unicorn 4.0.7 - thanks
