### ISSUE TITLE
Issue when running Gulp Tasks

### ISSUE THREAD

**Issue by tanakamapondera** [muso31/Helixbase#16]
Hi.

So I keep running into an issue whenever I use the gulp task command which is rather frustrating and I not sure what I'm doing wrong.
![1](https://user-images.githubusercontent.com/43476830/52083416-59d05800-256d-11e9-9a35-c4afb03568b4.PNG)
![2](https://user-images.githubusercontent.com/43476830/52083417-59d05800-256d-11e9-9d2d-d920e65dc6c9.PNG)

The red text in the first picture is repeated several times, but for different files, before I get what you see in the second picture.
Any ideas? Thanks!

**Comment by muso31** [comment]
Hi this issue could relate to your visual studio installation, depending which options you selected during the installation procedure. You may need to configure the installation options to install web development build tools or try downloading the likes of https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15

**Comment by tanakamapondera** [comment]
Oh wow. Thank you for the quick response! Never would have guessed that it might have to do with VS. 
I thought I had done something wrong with my Helixbase project setup.
Will look into the matter. Thanks again!

**Comment by tanakamapondera** [comment]
You were right, that was the issue. Really appreciate the help!
