### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by devarjunan** [muso31/Helixbase#20]
Hi 

I have taken latest build and tried in my local environment. Helixbase.Website project seems failing.

17>Using "CollectFilesinFolder" task from assembly "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\Web\Microsoft.Web.Publishing.Tasks.dll".
17>Task "CollectFilesinFolder"
17>Done executing task "CollectFilesinFolder" -- FAILED.
17>Done building target "CollectAdditionalFilesToRemoveFromTarget" in project "Helixbase.Website.csproj" -- FAILED.
17>
17>Build FAILED.
17>    0 Warning(s)
17>    0 Error(s)
17>
17>Time Elapsed 00:00:05.63
========== Rebuild All: 16 succeeded, 1 failed, 0 skipped ==========

I have attached build output for reference.
[Build error.txt](https://github.com/muso31/Helixbase/files/2964419/Build.error.txt)

**Comment by richardszalay** [comment]
This looks like an issue with HPP. Let me look into it and get back to you. If it's a bug with HPP itself, I'll create a bug there and cross reference it here.

**Comment by richardszalay** [comment]
Just to clarify: you just cloned the repo and built in VS? Did the target folder (in Local.pubxml) exist?

**Comment by devarjunan** [comment]
I have downloaded as zip file, extract and build in local environment. I have done changes in Local.pubxml as per my sitecore environment

**Comment by richardszalay** [comment]
Can you try launching VS as Administrator? It's possible that you need elevated privelages to write to your target folder and HPP isn't dealing with the error.

**Comment by richardszalay** [comment]
Last question: is your publishUrl property a folder or an http:// URI? It needs to be a folder

**Comment by devarjunan** [comment]
I have opened visual studio as administrator and still getting same issue. I have done 2 changes after downloading the source from Github

1. Local.pubxml - changed publish url to local sitecore instance folder
<PublishUrl>C:\inetpub\wwwroot\sxa.local</PublishUrl>

2. Updated source path in z.Common.Devsettings.Config

**Comment by richardszalay** [comment]
@devarjunan Right. I _think_ I understand the issue. If I'm right, there's work to be done on HPP ~~but I have a workaround for you for the time being.~~

~~Can you try to right-click Publish the Website project to the "Local" profile. If that succeeds, try building again and let me know if that fixes it.~~

Scratch that, the only workaround would be unnecessarily arduous. I've fixed the underlying issue and will do a release soon.

**Comment by richardszalay** [comment]
Fix published as HPP 1.5.2

Update your Website project's `RichardSzalay.Helix.Publishing.WebRoot` reference to `1.5.2`, build and everything should work. I've updated Helixbase already.

Thanks for reporting the issue! Can you close it once you've confirmed the fix to be working?

**Comment by devarjunan** [comment]
Perfect. Build is successful. Thanks a lot for quick fix :)
