### ISSUE TITLE
Unicorn Issues on initial sync - Sitecore 9.1.1

### ISSUE THREAD

**Issue by deeja** [muso31/Helixbase#24]
_Note: I resolved a log on issue by setting the [Unicorn.UI.IdentityServer.config `Build Action` to `Content`](https://github.com/SitecoreUnicorn/Unicorn/issues/326#event-2048102838)_

On the first sync, I am receiving these warnings/errors

![image](https://user-images.githubusercontent.com/174247/57013247-7c245100-6c02-11e9-9401-0cd524dbfe58.png)
![image](https://user-images.githubusercontent.com/174247/57013257-89414000-6c02-11e9-87f1-c12ba1917947.png)
![image](https://user-images.githubusercontent.com/174247/57013270-99591f80-6c02-11e9-8006-0cc0ebc5d003.png)
![image](https://user-images.githubusercontent.com/174247/57013274-a118c400-6c02-11e9-840e-eea8a756e1b1.png)

**Comment by richardszalay** [comment]
Did you update `sourceFolder` in [z.Common.DevSettings.config](https://github.com/muso31/Helixbase/blob/master/src/Project/Common/code/App_Config/Include/Project/z.Common.DevSettings.config#L3) to reflect your local repository?

**Comment by muso31** [comment]
@deeja  I've included the missing config as content but the issues you're experiencing do appear to be a missing _sourceFolder_
