### ISSUE TITLE
Include view precompilation

### ISSUE THREAD

**Issue by richardszalay** [muso31/Helixbase#26]
Precompiling razor views can improve startup performance and using [RazorGenerator.MsBuild](https://github.com/RazorGenerator/RazorGenerator/wiki/Using-RazorGenerator.MsBuild) it has a negligible impact on build performance. What are your thoughts on including it OOTB?

This should also be added to the templates added via #25

**Comment by muso31** [comment]
Last time I used precompiled razor views it caused a lot more issues than it was worth, have you used them before? They could be more reliable now as this was over a year ago

**Comment by richardszalay** [comment]
Using the out of the build compilation (aspnet_compiler.exe), I'd agree.

RazorGenerator.MsBuild takes a different approach by generating .cs file as part of the build (if they've changed since the last build), and including the compiled views in the main assembly.

**Comment by muso31** [comment]
Ok cool let's look into it!

**Comment by steviemcg** [comment]
I use RazorGenerator.MsBuild on a client project and it's saved my bacon a few times!

**Comment by muso31** [comment]
I'll get this added at some point, have been working with RazorGenerator.MsBuild also with good results, especially for PaaS startup times

**Comment by muso31** [comment]
Added, finally :) https://github.com/muso31/Helixbase/commit/da3769ae90fdc40734e5032a184fa08124c4ca3b
