### ISSUE TITLE
AllTemplatesIndexField is not computed

### ISSUE THREAD

**Issue by rkeitel** [muso31/Helixbase#38]
In the foundation module "Search" the index field "alltemplates" is not created. The class "AllTemplatesIndexField" must inherit from "Sitecore.ContentSearch.ComputedFields.AbstractComputedIndexField".

**Comment by muso31** [comment]
thanks @rkeitel this is now resolved https://github.com/muso31/Helixbase/commit/66285d1a345cba16cd5178f668dd17f571424eeb
