### ISSUE TITLE
The Hero component always saves Images to data source /Hero 1 when using Experience Editor

### ISSUE THREAD

**Issue by JuliusAngwenyi** [muso31/Helixbase#40]
I noticed when using the custom Experience button to select Hero images, this are always saved to data source location `/sitecore/content/Helixbase/Global/Hero Items/Hero 1 ` even when the component  is pointed to data source location `/sitecore/content/Helixbase/Global/Hero Items/Hero 2` for example.

To recreate, in Experience Editor:

- change the data source location to /sitecore/content/Helixbase/Global/Hero Items/Hero 2

- save your changes

- click on 'Select Hero Images' custom experience editor

- on the Hero Image dialog, update the selected list (add or remove). 

- save your changes

You will notice these changes were actually made to /sitecore/content/Helixbase/Global/Hero Items/Hero 1 instead of Hero 2

**Comment by muso31** [comment]
Thanks for this @JuliusAngwenyi - personalization was enabled on the rendering, this is now removed
