### ISSUE TITLE
Intellisense in Razor views

### ISSUE THREAD

**Issue by muso31** [muso31/Helixbase#46]
Since updating to the SDK project format helpers such as Html.Sitecore() will throw an error:

IHtmlHelper<dynamic> does not contain a definition for Sitecore

**Comment by JOliverXC** [comment]
Is there a workaround for this? IntelliSense is something I can deal with but because razor precompiles on build it prevents projects from building. This makes creating SXA components pretty much impossible because you cannot use the decorators.

**Comment by muso31** [comment]
The workaround for now would be to use the non sdk project format and update the packages to 9.3... https://github.com/muso31/Helixbase/tree/feature/9.2.0

It seems the new project format doesn't play well with the Sitecore helpers

**Comment by nehemiahj** [comment]
Is this issue related the below observation? 
With the latest Helixbase project, using Sitecore Rocks Visual Studio Add Item Templates are not possible. Reason may be the Helixbase projects are .Net Core Web projects and only Razor views allowed (??) .

**Comment by muso31** [comment]
Hi @nehemiahj yes it will be the same issue, I'll create a branch for a none sdk version of Helix Base 9.3 when I can

**Comment by muso31** [comment]
To resolve this, I have added a branch for the [old csproj project format](https://github.com/muso31/Helixbase/tree/feature/9.3.0-old-csproj)
