### ISSUE TITLE
Proper order of operations for adding a project?

### ISSUE THREAD

**Issue by benjaminhigginsliquid** [muso31/Helixbase#47]
Helix Examples and this repository both share in the same conceptual IDE setup, so with that in mind I'm posing my question here as it pertains to both. How are developers expected to add new projects to a Visual Studio setup like this?

The requirements based on the existing projects and the Directory.Build.Props file indicate that we are to create projects whose .csproj file lives directly under folders called "website", under folders within their related Helix pillar, (arbitrarily) titled in the format {Pillar.ProjectName},

My common intuition tells me to do the following after observing the existing structure:

1. Create a physical folder directly under Feature: "MyProject",
2. Add a "MyProject" solution folder to mimic the same structure within Visual Studio.
3. Right click on this solution folder, add new project, and set the Location to the MyProject physical folder created in step 1

At this point I've hit my first problem; whatever I name the project, will become the name of the folder. There is no Visual Studio 2019 option I am aware of that lets you specify that you wish to ether create a project (AKA place the csproj) directly into an existing folder, or name the created folder something other than the project.

If I decided I would just name the project "website", so that the folder is made, then rename it post-creation, I run into a second problem: Visual Studio believes a project named "website" already exists. The details of why this is happening is not something I have research, but this seems to be a prevalent "issue" in Visual Studio that has persisted for several years but has never accrued enough interest to warrant a fix.

Ultimately, the only solution we've found to actually work is to copy an existing project and manually adjust several folders and csproj values, which feels counter-intuitive to any developer we would like to be able to "plug and dev".

Please let me know what the expected order of operations here are for performing this common dev task, as the Helix conventions indirectly encourage lots of projects by way of highly module design, but the overhead for any developer to figure out how to create a project (and ensure that they created it properly) currently seems egregious.

**Comment by muso31** [comment]
Hi, it's a bit outdated but if you're adding projects manually you can use a step by step guide.. https://nshackblog.wordpress.com/2017/03/27/step-by-step-adding-a-project-to-a-helix-solution/

Or have you considered [Sitecore Helix visual studio templates](https://marketplace.visualstudio.com/items?itemName=AndersLaublaubplusco.SitecoreHelixVisualStudioTemplates)?

**Comment by benjaminhigginsliquid** [comment]
Thanks for the reply Neil, both look like viable approaches, we're looking for a consistent approach to communicate to developers and we can definitely derive some instruction based on choosing one pf these (the VS templates are a bit out of date at the moment and use a different deployment setup that what we're used to, but the ease of creation is much more preferable). 

Thanks for putting those out there. They were hidden on the internet otherwise to us!
