### ISSUE TITLE
Upgrade Helixbase.Website.csproj to SDK project style

### ISSUE THREAD

**Issue by sshushliapin** [muso31/Helixbase#58]
Is there any reason why Helixbase.Website.csproj project has not been updated to SDK style? Looks like all the other projects (e.g. [Helixbase.Project.Common.csproj](https://github.com/muso31/Helixbase/blob/master/src/Project/Common/website/Helixbase.Project.Common.csproj#L1)) uses `Sdk="Microsoft.NET.Sdk"`.

**Comment by muso31** [comment]
@sshushliapin the [HPP ](https://github.com/richardszalay/helix-publishing-pipeline) project doesn't support the SDK project style. It's no longer support so it's unlikely to do so unless someone creates a pr
