### ISSUE TITLE
Invalid option 'latestMajor' for /langversion. Use '/langversion:?' to list supported values.

### ISSUE THREAD

**Issue by DheerajP** [muso31/Helixbase#59]
Hi,

Getting this on project build. I am on VS 15.9.45.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1617	Invalid option 'latestMajor' for /langversion. Use '/langversion:?' to list supported values.	Helixbase.Website	C:\Projects\Helix\src\Website\website\CSC	1	N/A

**Comment by muso31** [comment]
You can change the language version on the following file: 

https://github.com/muso31/Helixbase/blob/master/src/Website/website/Directory.build.props#L6
