### ISSUE TITLE
How to run last step? run unicorn?

### ISSUE THREAD

**Issue by abajorunas** [muso31/Helixbase#6]
for me going MySitecoreSite.com/unicorn.aspx results in page not found.

please help

**Comment by muso31** [comment]
Hi, ensure you have the correct values set in [z.Helixbase.DevSettings.config](https://github.com/muso31/Helixbase/blob/master/src/Project/Helixbase/code/App_Config/Include/Project/z.Helixbase.DevSettings.config) and [gulp-config.js](https://github.com/muso31/Helixbase/blob/master/gulp-config.js)

Ensure that the NuGet restore was successful and the full publish completed, then send any info from the logs, thanks

**Comment by abajorunas** [comment]
thanks for quick reply,
yes, nuget and publish was completed successfully.

but when I want to access unicorn I see the following.

![image](https://user-images.githubusercontent.com/26685987/31379047-e05e826a-adb5-11e7-9b6a-69a614ed1dfa.png)

`[12:35:37] MSBuild complete!
[12:35:37] Building project: src\Foundation\ORM\code\Helixbase.Foundation.ORM.csproj
[12:35:37] Building project: 1 item
  Helixbase.Foundation.Common -> C:\project\Helixbase\src\Foundation\Common\code\bin\Helixbase.Foundation.Common.dll
  Copying all files to temporary location below for package/publish:
  obj\Debug\Package\PackageTmp.
  Helixbase.Foundation.ORM -> C:\project\Helixbase\src\Foundation\ORM\code\bin\Helixbase.Foundation.ORM.dll
  Copying all files to temporary location below for package/publish:
  obj\Debug\Package\PackageTmp.
[12:35:38] MSBuild complete!
[12:35:38] Building project: src\Foundation\Search\code\Helixbase.Foundation.Search.csproj
[12:35:38] Building project: 1 item
  Helixbase.Foundation.Search -> C:\project\Helixbase\src\Foundation\Search\code\bin\Helixbase.Foundation.Search.dll
  Copying all files to temporary location below for package/publish:
  obj\Debug\Package\PackageTmp.
[12:35:39] MSBuild complete!
[12:35:39] Building project: src\Foundation\Serialization\code\Helixbase.Foundation.Serialization.csproj
[12:35:39] Building project: 1 item
  Helixbase.Foundation.Serialization -> C:\project\Helixbase\src\Foundation\Serialization\code\bin\Helixbase.Foundation.Serialization.dll
  Copying all files to temporary location below for package/publish:
  obj\Debug\Package\PackageTmp.
[12:35:40] MSBuild complete!
Process terminated with code 0.
`

**Comment by abajorunas** [comment]
my bad, bad config. sorry
