### ISSUE TITLE
assets unpublished

### ISSUE THREAD

**Issue by muso31** [muso31/Helixbase#61]
Since the latest update to 10.3 which has also introduced central package management, configs and views are not being published by HPP

**Comment by sshushliapin** [comment]
I'm using central package management with build scripts from (recently archived) [Sitecore MVP repo](https://github.com/Sitecore/MVP-Site/tree/main/_Build/props). Works great.

**Comment by navancommits** [comment]
Please merge this at the earliest else the VS publish doesn't work as expected: https://github.com/muso31/Helixbase/pull/62

**Comment by muso31** [comment]
resolved in #62
